version: "3.9"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: es01
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
  kib01:
    image: docker.elastic.co/kibana/kibana:8.6.1
    container_name: kib01
    ports:
      - "5601:5601"
    depends_on:
      - es01
    networks:
      - elastic
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
volumes:
  es_data:
    driver: local
networks:
  elastic:
    driver: bridge
